# This rule is not used by the project k8sible itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to k8sible.core.k8sible.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8sible
    app.kubernetes.io/managed-by: kustomize
  name: k8sibleworkflow-viewer-role
rules:
- apiGroups:
  - k8sible.core.k8sible.io
  resources:
  - k8sibleworkflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8sible.core.k8sible.io
  resources:
  - k8sibleworkflows/status
  verbs:
  - get
