# This rule is not used by the project k8sible itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over k8sible.core.k8sible.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8sible
    app.kubernetes.io/managed-by: kustomize
  name: k8sibleworkflow-admin-role
rules:
- apiGroups:
  - k8sible.core.k8sible.io
  resources:
  - k8sibleworkflows
  verbs:
  - '*'
- apiGroups:
  - k8sible.core.k8sible.io
  resources:
  - k8sibleworkflows/status
  verbs:
  - get
