# This rule is not used by the project k8sible itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the k8sible.core.k8sible.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8sible
    app.kubernetes.io/managed-by: kustomize
  name: k8sibleworkflow-editor-role
rules:
- apiGroups:
  - k8sible.core.k8sible.io
  resources:
  - k8sibleworkflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8sible.core.k8sible.io
  resources:
  - k8sibleworkflows/status
  verbs:
  - get
