apiVersion: k8sible.core.k8sible.io/v1alpha1
kind: K8sibleWorkflow
metadata:
  labels:
    app.kubernetes.io/name: k8sible
  name: k8sibleworkflow-sample
  namespace: k8sible
spec:
  source:
    repository: https://github.com/bensonphillipsiv/k8sible
    reference: main
    secretRef:
      name: k8sible-git-credentials
  apply:
    path: test/ansible/apply_ansible.yaml
    maxRetries: 1
  reconcile:
    path: test/ansible/reconcile_ansible.yaml
    schedule: "*/15 * * * *"
    maxRetries: 1
  failureCycleCooldown: 5m
