apiVersion: k8sible.core.k8sible.io/v1alpha1
kind: K8sibleWorkflow
metadata:
  labels:
    app.kubernetes.io/name: k8sible
  name: k8sibleworkflow-sample
  namespace: k8sible
spec:
  source:
    repository: https://github.com/bensonphillipsiv/k8sible
    reference: main
    path: test/ansible/test_ansible.yaml
  schedule: "0 2 * * *"
  reconcile:
    source:
      path: examples/sample-reconcile
    schedule: "0 3 * * *"

  secretRef:
    name: k8sible-creds
